General fixes and changes to sync with the work done in Online Services
juju-solutions/kubernetes-demos pull request #6
Opened 2017-03-03 13:09 UTC by caio1982

I understand some of these changes might be just cosmetics and not entirely desirable but here they all are:

- Jenkins root-disk minimal size had to be bumped so I could test multiple builds in the same deployment
- Uses env-template for variable substitution, although I think both replace-image-tag.sh and deploy-to-kubernetes.sh could end up being a single "control" script later.
- The DOMAIN var will be sorted later but it is passed on like the others
- IMAGE_TAG is actually the Git commit hash now, to better track what had been deployed

See https://pastebin.canonical.com/181433/ for a "workflow" after it is all done:

1. Commit/push to the app repo
2. Tested the dev env for the specific Git commit hash
3. Trigger the Jenkins job passing "qa" as namespace (it took 7 seconds for it to be up and live)
4. QA'ed changes and did the same as before but passing "prod" as namespace
5. Celebrated

2017-03-03 13:10 UTC, caio1982 commented
Please squash it before doing anything with those changes. My apologies for the dirty commit history this time, ugh.

2017-03-04 00:05 UTC, lazypower requested changes
I see some good work in here. Once you've squashed the commit history I'll be happy to approve and merge.

2017-03-04 00:05 UTC, chuckbutler commented on setup.sh
> +juju deploy jenkins.yaml
+1 on the topical rename here.

2017-03-04 00:05 UTC, chuckbutler commented on workspaces/deploy-to-kubernetes/config.xml
> +          <name>IMAGE_OWNER</name>
Ah interesting! parameterized the build with registry details. +1

2017-03-04 00:05 UTC, chuckbutler commented on workspaces/mm-container-build/config.xml
> +      <repoTag>${GIT_COMMIT}</repoTag>
+1 on this identifier moving through. I like the idea of having the git commit be the unique identifier, until we get into having multiple revisions of that single git commit in all our ci infra, and trying to decouple what happened where. I think there's room for improvement here but I don't have a pliable solution today.

Perhaps this works fine as is and I'm over-thinking it too :)

2017-03-06 13:16 UTC, caio1982 commented
Done, just please don't forget about https://bitbucket.org/jujudemo/mattermost-deploy/pull-requests/1/sync-work-done-for-a-similar-app-in-online/diff too, as they are hand-in-hand :bowtie:

2017-03-07 15:01 UTC, merged

2017-03-07 15:01 UTC, chuckbutler commented
+1 LGTM

2017-03-07 16:10 UTC, mbruzek commented
I also looked over these changes and was unable to get my +1 before Chuck merged it!